version: "3.7"

services:
   mqtt:
      image: eclipse-mosquitto
      ports:
         - "1883:1883"
      volumes:
         - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

   mongodb:
      image: mongo:latest
      container_name: mongodb
      ports:
         - "27017:27017"
      volumes:
         - mongo_data:/data/db
      command: mongod --setParameter diagnosticDataCollectionEnabled=false

   mongo-express:
      image: mongo-express
      ports:
         - "8081:8081"
      environment:
         ME_CONFIG_MONGODB_SERVER: mongodb
      depends_on:
         - mongodb

   voice_profiling:
      build:
         context: ./processing_layer/user_profiling/voice_profiling
         dockerfile: Dockerfile
      ports:
         - "8000:8000"
      volumes:
         - ./processing_layer/user_profiling/voice_profiling:/app
      depends_on:
         - mongodb

   voice_metrics:
      build:
         context: ./processing_layer/metrics_computation/voice_metrics
         dockerfile: Dockerfile
      volumes:
         - ./processing_layer/metrics_computation/voice_metrics:/app
      depends_on:
         - mqtt
         - voice_profiling
         - mongodb

   temporal_context_modeling_layer:
      build:
         context: ./temporal_context_modeling_layer
         dockerfile: Dockerfile
      ports:
         - "8082:8082"
      depends_on:
         - mongodb

   # temporal-context:
   #    build: ./temporal-context
   #    ports:
   #       - "8082:8082"
   #    depends_on:
   #       - mongodb

   # streamlit:
   #    build:
   #       context: ./streamlit-app
   #       dockerfile: Dockerfile
   #    ports:
   #       - "8501:8501"
   #    depends_on:
   #       - mongodb
   #    environment:
   #       - PYTHONBUFFERED=1

volumes:
   mongo_data:
