version: "3.7"

services:
   mqtt:
      image: eclipse-mosquitto
      ports:
         - "1883:1883"
      volumes:
         - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

   mongodb:
      image: mongo:latest
      container_name: mongodb
      ports:
         - "27017:27017"
      volumes:
         - mongo_data:/data/db

   mongo-express:
      image: mongo-express
      ports:
         - "8081:8081"
      environment:
         ME_CONFIG_MONGODB_SERVER: mongodb
      depends_on:
         - mongodb

   streamlit:
      build:
         context: ./streamlit-app
         dockerfile: Dockerfile
      ports:
         - "8501:8501"
      depends_on:
         - mongodb
      environment:
         - PYTHONBUFFERED=1

   speech-processor:
      build:
         context: ./speech-processor
         dockerfile: Dockerfile
      volumes:
         - ./speech-processor:/app
      depends_on:
         - mqtt
         - mongodb

   user-recognition:
      build:
         context: ./user-recognition
         dockerfile: Dockerfile
      ports:
         - "8000:8000"
      volumes:
         - ./user-recognition:/app
      depends_on:
         - mongodb

   temporal-context:
      build: ./temporal-context
      ports:
         - "8082:8082"
      depends_on:
         - mongodb

volumes:
   mongo_data:
