version: "3.7"

services:
   mqtt:
      image: eclipse-mosquitto
      ports:
         - "1883:1883"
      volumes:
         - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

   mongodb:
      image: mongo:latest
      container_name: mongodb
      ports:
         - "27017:27017"
      volumes:
         - mongo_data:/data/db

   mongo-express:
      image: mongo-express
      ports:
         - "8081:8081"
      environment:
         ME_CONFIG_MONGODB_SERVER: mongodb
      depends_on:
         - mongodb

   dashboard:
      build:
         context: ./dashboard
         dockerfile: Dockerfile
      ports:
         - "4200:80"
      depends_on:
         - socket-server

   socket-server:
      build:
         context: ./socket-server
         dockerfile: Dockerfile
      ports:
         - "5051:5051"
      volumes:
         - ./socket-server:/app
      command: node server.js
      depends_on:
         - mqtt
         - mongodb

   speech-processor:
      build:
         context: ./speech-processor
         dockerfile: Dockerfile
      volumes:
         - ./speech-processor:/app
      depends_on:
         - mqtt
         - mongodb
         - socket-server

volumes:
   mongo_data:
